version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - git checkout master
      - npm install
  build:
    commands:
      - npm run pw
  post_build:
    commands:
      - echo "Node.js version:"
      - node --version
      - echo "Playwright installation check:"
      - npx playwright install
      - echo "Running Playwright tests:"
      - npx playwright test
