version: 0.2

phases:
  install:
    commands:
      - echo Installing dependencies
      - npm ci
      - npm install -D allure-playwright
  build:
    commands:
      - echo Running tests
      - npx playwright test